### ISSUE TITLE
HW 2 Grading

### ISSUE THREAD

**Issue by cdlockard** [UWSEDS-Au18/using-functions-khdusenbury#1]
# Homework 2 evaluation rubric: :

## Part A:

Task 1: Downloads file from web 
Points: 1 / 1

Task 2: Reads data into Python
Points: 1 / 1

Task 3: Creates data frame of at least 3 columns:
Points: 2 / 2

## Part B:

Function that:

Task 4: Checks that Dataframe contains the correct columns
Points: 1 / 1

Task 5: Checks that columns contain the correct data type:
Points: 1 / 1

Task 6: Checks that there are at least 10 rows:
Points: 1 /1 

# Grade: 7 / 7

Great job! Excellent use of constants to define expected types and columns, and nice use of ValueErrors to deal with incorrectly formatted data.

**Comment by khdusenbury** [comment]
Thanks!
